repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-byte-order-marker
        exclude: ^tests/.*
      - id: check-case-conflict
        exclude: ^tests/.*
      - id: check-merge-conflict
        exclude: ^tests/.*
      - id: check-symlinks
        exclude: ^tests/.*
      - id: check-yaml
        exclude: ^tests/.*
      - id: end-of-file-fixer
        exclude: ^tests/.*
      - id: mixed-line-ending
        exclude: ^tests/.*
      - id: trailing-whitespace
        exclude: ^tests/.*
      - id: end-of-file-fixer
        exclude: ^tests/.*
